---

- name: Configure Fedora Silverblue
  hosts: workstation
  vars_files:
    - vars/main.yml

  tasks:
    - name: Configure base settings for Fedora Silverblue
      when: ansible_distribution == "Fedora"
      tags: common
      ansible.builtin.import_role:
        name: common

    - name: Configure layered packages Fedora Linux Silverblue
      when: ansible_distribution == "Fedora"
      tags: layered_packages
      ansible.builtin.import_role:
        name: layered_packages

    - name: Configure Flatpaks for Fedora Silverblue
      when: ansible_distribution == "Fedora"
      tags: flatpaks
      ansible.builtin.import_role:
        name: flatpaks

    - name: Configure Gnome for Fedora Linux
      when: ansible_distribution == "Fedora"
      tags: gnome_settings
      ansible.builtin.import_role:
        name: gnome_settings

    - name: Configure OSTree for Fedora Silverblue
      when: ansible_distribution == "Fedora"
      tags: os_updates
      ansible.builtin.import_role:
        name: os_updates